#!/bin/bash

# activate env variables in .env file
set -a
source .env.docker
set +a

docker build \
    --build-arg NEXT_PUBLIC_SUPABASE_URL="$NEXT_PUBLIC_SUPABASE_URL" \
    --build-arg NEXT_PUBLIC_SUPABASE_REDIRECT_URL="$NEXT_PUBLIC_SUPABASE_REDIRECT_URL" \
    --build-arg NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY="$NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY" \
    -t front .

# run the container with env variables
docker run -e VESTA_API_KEY="$VESTA_API_KEY" \
    -e VESTA_API_URL="$VESTA_API_URL" \
    -e NEXT_PUBLIC_SUPABASE_URL="$NEXT_PUBLIC_SUPABASE_URL" \
    -e NEXT_PUBLIC_SUPABASE_REDIRECT_URL="$NEXT_PUBLIC_SUPABASE_REDIRECT_URL" \
    -e NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY="$NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY" \
    -p 3000:3000 \
    front